# Generated by Django 5.0 on 2023-12-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_artigo_data_criacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigo',
            new_name='ComentarioModel',
        ),
    ]
