# Generated by Django 5.0 on 2023-12-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_delete_quillcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='comentarios',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
